Ejercicio1Cliente/Ejercicio1Cliente/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ejercicio1Cliente.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)//constructor de la clase
        { }

        public DbSet<Cliente> Cliente { get; set;}
    }
}

Ejercicio1Cliente/Ejercicio1Cliente/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ejercicio1Cliente.Models
{
    public class Cliente
    {
        [Key]
        [Display(Name = "Id del cliente")]
        public int Clienteid { get; set; }

        [Display(Name = "Nombre del cliente")]
        [Required(ErrorMessage = "Ingresa el nombre del cliente")]
        public string Clientenombre { get; set; }

        [Display(Name = "Credito del cliente")]
        [Required(ErrorMessage = "Ingresa el credito del cliente")]
        public int Creditocliente { get; set; }

        [Display(Name = "Edad del cliente")]
        [Required(ErrorMessage = "Ingresa la edad del cliente")]
        [Range(18,70)]
        public int Edadcliente { get; set; }

        [Display(Name = "Correo del cliente")]
        [Required(ErrorMessage = "Ingresa el correo del cliente")]
        [EmailAddress(ErrorMessage = "El formato del correo ingresado no es valido")]
        public string Correocliente { get; set; }
    }
}

Ejercicio1Cliente/Ejercicio1Cliente/Models/ErrorViewModel.cs
using System;

namespace Ejercicio1Cliente.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ejercicio1Cliente/Ejercicio1Cliente/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ejercicio1Cliente.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ejercicio1Cliente.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var mostrarDatos = _db.Cliente.ToList();
            return View(mostrarDatos);
        }

        [HttpGet]
        public async Task<IActionResult> Index(String buscaCliente)
        {
            ViewData["DetalleCliente"] = buscaCliente;
            var buscaClienteQuery = from x in _db.Cliente select x;
            if(!String.IsNullOrEmpty(buscaCliente))
            {
                buscaClienteQuery = buscaClienteQuery.Where(x => x.Clientenombre.Contains(buscaCliente) || x.Correocliente.Contains(buscaCliente));
            }
            return View(await buscaClienteQuery.AsNoTracking().ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Cliente nuevoCliente)
        {
            if(ModelState.IsValid)
            {
                _db.Add(nuevoCliente);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nuevoCliente);
        }

        public async Task<IActionResult> Detail(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEmpleado = await _db.Cliente.FindAsync(id);
            return View(detalleEmpleado);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEmpleado = await _db.Cliente.FindAsync(id);
            return View(detalleEmpleado);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (Cliente actualizarCliente)
        {
            if(ModelState.IsValid)
            {
                _db.Update(actualizarCliente);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(actualizarCliente);
        }

        public async Task<IActionResult> Delete (int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            var detalleEmpleado = await _db.Cliente.FindAsync(id);
            return View(detalleEmpleado);
        }

        [HttpPost]
        public async Task<IActionResult> Delete (int id)
        {
            var detalleEmpleado = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(detalleEmpleado);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Ejercicio1Cliente/Ejercicio1Cliente/Views/Cliente/Create.cshtml
@model Ejercicio1Cliente.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Crear un nuevo cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Clientenombre" class="control-label"></label>
                <input asp-for="Clientenombre" class="form-control" />
                <span asp-validation-for="Clientenombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditocliente" class="control-label"></label>
                <input asp-for="Creditocliente" class="form-control" />
                <span asp-validation-for="Creditocliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edadcliente" class="control-label"></label>
                <input asp-for="Edadcliente" class="form-control" />
                <span asp-validation-for="Edadcliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correocliente" class="control-label"></label>
                <input asp-for="Correocliente" class="form-control" />
                <span asp-validation-for="Correocliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista de empleados</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ejercicio1Cliente/Ejercicio1Cliente/Views/Cliente/Delete.cshtml
@model Ejercicio1Cliente.Models.Cliente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Seguro que quieres eliminar el cliente?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clienteid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clienteid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clientenombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clientenombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creditocliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creditocliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edadcliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edadcliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correocliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correocliente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la lista de clientes</a>
    </form>
</div>

Ejercicio1Cliente/Ejercicio1Cliente/Views/Cliente/Detail.cshtml
@model Ejercicio1Cliente.Models.Cliente

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalle del Cliente</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clienteid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clienteid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clientenombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clientenombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creditocliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creditocliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edadcliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edadcliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correocliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correocliente)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Clienteid}) 
    <a asp-action="Index">Regresar a la lista de clientes</a>
</div>

Ejercicio1Cliente/Ejercicio1Cliente/Views/Cliente/Edit.cshtml
@model Ejercicio1Cliente.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1>Actualizar un cliente</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Clienteid" class="control-label"></label>
                <input asp-for="Clienteid" class="form-control" readonly />
                <span asp-validation-for="Clienteid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clientenombre" class="control-label"></label>
                <input asp-for="Clientenombre" class="form-control" />
                <span asp-validation-for="Clientenombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creditocliente" class="control-label"></label>
                <input asp-for="Creditocliente" class="form-control" />
                <span asp-validation-for="Creditocliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edadcliente" class="control-label"></label>
                <input asp-for="Edadcliente" class="form-control" />
                <span asp-validation-for="Edadcliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Correocliente" class="control-label"></label>
                <input asp-for="Correocliente" class="form-control" />
                <span asp-validation-for="Correocliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar a la lista de clientes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ejercicio1Cliente/Ejercicio1Cliente/Views/Cliente/Index.cshtml
@model IEnumerable<Ejercicio1Cliente.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Empleados</h1>

<p>
    <a asp-action="Create">Crear un nuevo cliente</a>
</p>

<form asp-action="Index" method="get">
    <input type="search" placeholder="Ingresa nombre o correo electronico" name="buscaCliente" 
           value=@ViewData["DetalleCliente"] style="width:500px;"/>
    <input type="submit" name="value" class="btn btn-primary"/>
    <a asp-action="Index">Ver todos</a>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Clienteid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Clientenombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Creditocliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edadcliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correocliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Clienteid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clientenombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creditocliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edadcliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correocliente)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Clienteid }, new {@class = "btn btn-primary" }) 
                @Html.ActionLink("Detail", "Detail", new { id = item.Clienteid }, new { @class = "btn btn-success" }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.Clienteid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Ejercicio1Cliente/Ejercicio1Cliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ejercicio1Cliente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">Ejercicio1Cliente</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>